--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Terpz710/ToastBroadcaster
build-by-default: true
branches:
- main
projects:
  ToastBroadcaster:
    path: ""
    lint:
      phpstan: true
...
