name: ToastBroadcaster
main: NoobMCBG\ToastBroadcaster\ToastBroadcaster
api: 4.11.0
version: 1.0.0
author: NoobMCBG
description: Create toast style notifications for all your players
website: https://github.com/NoobMCBG/ToastBroadcaster