---
name: ToastBroadcaster
main: NoobMCBG\ToastBroadcaster\ToastBroadcaster
api:
- 5.0.0
version: 1.0.2
author: NoobMCBG, Terpz710
description: Create toast style notifications for all your player
website: https://github.com/NoobMCBG/ToastBroadcaster
...
